# Generated by Django 5.1.5 on 2025-01-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
