# Generated by Django 5.1.5 on 2025-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(verbose_name=models.CharField(max_length=100, unique=True))),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, default='/media/platforms/logo.png', null=True, upload_to='')),
            ],
        ),
    ]
