# Generated by Django 5.1.5 on 2025-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initiated'), (2, 'Confirmed'), (-1, 'Cancelled'), (3, 'Paid')]),
        ),
    ]
